### ISSUE TITLE
Encoding should return string and never fail

### ISSUE THREAD

**Issue by cmbrandenburg** [alicemaz/rust-base64#1]
This crate provides no function for base64-encoding a `&[u8]` into a `String`. Instead, it provides the following two functions: 

```rust
pub fn encode(input: &str) -> Result<String, Base64Error>
pub fn u8en(bytes: &[u8]) -> Result<Vec<u8>, Base64Error>
```

I.e., the crate does string-to-string encoding and blob-to-blob encoding, but not blob-to-string encoding—which is what base64-encoding is all about.

Furthermore, encoding cannot fail, so why do these functions return a `Result`? This puts an undue burden on the application, which must either check for an error that won't happen or else call `unwrap()` on the result.

I propose a single function like this:

```rust
pub fn encode(bytes: &[u8]) -> String
```

Rust already makes it easy to convert any string to a `&[u8]`, so this one function handles every case the existing two functions already handle. Also:

1. It's more type-safe because it doesn't type-erase away the fact that the output is always UTF-8, and,
1. It's more ergonomic because there's no error case for the application to deal with.

**Comment by oleid** [comment]
I just stumbled across the very same issue and had the very same thoughts.

**Comment by alicemaz** [comment]
Thank you for the suggestions (and sorry it took me so long, yeesh!) Returning Result from encode was an oversight on my part. Changing the return types I was iffy on for awhile but have come to agree you are correct and that this is the more sensible design.

**Comment by cmbrandenburg** [comment]
Awesome and thanks!
