### ISSUE TITLE
Padding not needed on URL_SAFE

### ISSUE THREAD

**Issue by Keats** [alicemaz/rust-base64#10]
See https://github.com/rust-lang-nursery/rustc-serialize/blob/master/src/base64.rs#L183-L187 for what rustc-seralize does

That means that right now any URL_SAFE base64 string generated by a library that does that will not be decoded properly.

I believe the encode should skip padding on URL_SAFE mode and the decode should work the same even if the padding if missing (ie decoding `c0zGLzKEFWj0VxWuufTXiRMk5tlI5MbGDAYhzaxIYjo=` and `c0zGLzKEFWj0VxWuufTXiRMk5tlI5MbGDAYhzaxIYjo1` should yield the same result)

**Comment by alicemaz** [comment]
to follow up on discussion in #9, I've confirmed `c0zGLzKEFWj0VxWuufTXiRMk5tlI5MbGDAYhzaxIYjo=` and `c0zGLzKEFWj0VxWuufTXiRMk5tlI5MbGDAYhzaxIYjo` indeed decode to the same value. the second string you pasted is `c0zGLzKEFWj0VxWuufTXiRMk5tlI5MbGDAYhzaxIYjo*1*`, is this the cause of the difference? if there is a case of a properly padded and an unpadded base64 string decoding differently I would consider it a bug

**Comment by Keats** [comment]
Sorry, I missed that. That bug was my mistake, not `base64`
Closing that issue
