### ISSUE TITLE
Got DecodeError::InvalidLength in 0.10.1, but not in 0.9.3

### ISSUE THREAD

**Issue by timbru** [alicemaz/rust-base64#107]
Hi,

I am not sure if this is known issue, but I tried upgrading from 0.9.3 to 0.10.1 in my project, and now base64 that I could decode before using:

```base64::decode_config(&string, base64::MIME)```

Now breaks with a DecodeError::InvalidLength in 0.10.1, using:
```base64::decode_config(&string, base64::STANDARD_NO_PAD)```

Same for:
```base64::STANDARD``. 

I also tried:
```base64::decode_config(&string, base64::STANDARD_NO_PAD.decode_allow_trailing_bits(true))```

This is the base64 I tried to decode, which should be a valid DER x509 certificate when decoded.

`
MIID9TCCAt2gAwIBAgIJAN3oDHIqKat0MA0GCSqGSIb3DQEBCwUAMC0xKzApBgNV
BAMTIkR1bW15IG5hbWUgZm9yIGNlcnRpZmljYXRlIHJlcXVlc3QwHhcNMTEwNzAx
MDQwNzI0WhcNMTEwNzMxMDQwNzI0WjAtMSswKQYDVQQDEyJEdW1teSBuYW1lIGZv
ciBjZXJ0aWZpY2F0ZSByZXF1ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEArq33oZG7/cq8x0ywS/K5LlNeI5xk4LBZ3FVGzOpAOLAGrnxFR+q4WyJ3
mqlH2tPAjgf8tUiiXGmyBYehON36fK8jELs2k5YwwLoZQttS0UkCX6kY9Mzn5x47
W96NKjrBNiomGSiU+UTsmUn7BolI2/ZiwdZwel0WSCICh7EgAeraCJbGi2MDlGKQ
+2GPhoiLrTCRge/DYvVtBtI7dLCp6jhvyVIv0KYSXtZ+z31AlukMW6khBtEAhve+
+yqkQXmG72Bn3MvuJ1vozX+pki3E/BfSnt3/luJVJByUuz22SF+Dh9BsVj8TtoT5
1g+DrFLitPtIpo1SWwKOXrs4XpBMbwIDAQABo4IBFjCCARIwDwYDVR0TAQH/BAUw
AwEB/zAdBgNVHQ4EFgQUvVwQP/y4jndc/3/rNbih8OXT7E0wDgYDVR0PAQH/BAQD
AgEGMGoGCCsGAQUFBwELBF4wXDAoBggrBgEFBQcwBYYccnN5bmM6Ly9sb2NhbGhv
c3Q6NDQwNC9ycGtpLzAwBggrBgEFBQcwCoYkcnN5bmM6Ly9sb2NhbGhvc3Q6NDQw
NC9ycGtpL3Jvb3QubW5mMCEGCCsGAQUFBwEIAQH/BBIwEKAOMAwwCgIBAAIFAP//
//8wJwYIKwYBBQUHAQcBAf8EGDAWMAkEAgABMAMDAQAwCQQCAAIwAwMBADAYBgNV
HSABAf8EDjAMMAoGCCsGAQUFBw4CMA0GCSqGSIb3DQEBCwUAA4IBAQABBgG40cDo
Q0wEdfHjNpRMe3ibM6DFQKemQG9YSxgG1Cg9o8mjEZ1erF0PoqVmkdbmofkEBJMe
2UTly528jQhXf3qr4P/drs1otDHO/5y874SULA+eMACZ8o2bBzP/r/BFrgw211nY
iw0TIiwXMagwzVHtMTe0bb8IDkPJ3f3QzpUBZWIPOuOx2UlB8WKE1glZ7YyHALPl
FUWUfUVaVvo7Ylovmb+2OGMefl9JaJeODKOxrMW9b3duQ0dKgzgRpDd+uOLHlKPR
CXKs4wBrMLaIVqxCgdR1fJIrGKxJX2qhGiouq1aH9KNr2V+gU23tbUBSjSbmNYbw
IYc5/k2M7lo7
`

**Comment by marshallpierce** [comment]
0.10 removed whitespace stripping, which may be the cause here. If you want the old logic, it is simply `filter(|b| !b" \n\t\r\x0b\x0c".contains(b)` applied to the input byte vec.

**Comment by timbru** [comment]
Okay, I can use this and work around it. If it's just me asking, don't bother with the below. It's not that critical. 

But.. if there are others who try to do things with PEM encoded X509 certificates and/or MIME, then it 
it would be great if the library had config options for this. Like allowing it to ignore whitespace (in particular newlines), perhaps with a default to 'false' and a method like the one for allowing trailing bits. Nicer still would it be to also have a const for PEM (RFC1421), and/or MIME (RFC2045) - I think the difference is the padding, so PEM would be the same as MIME_NO_PAD I suppose.

I will leave it to you to decide if you are open to this and close the issue. If you are willing to support this in future, I would be very happy and interested.

Thanks

**Comment by marshallpierce** [comment]
It's not just you, but I don't think it's a good thing to put in this library. See #105 for another person asking quite insistently. There are a couple of problems: it complicates (and slows down) the implementation, but perhaps more relevant to this aspect, is that there's no end to the special cases. There are a million ways that base64 could be packaged, and it's not reasonable to try to handle them all. What kind of whitespace should be ignored, for instance? Newlines? Carriage returns? Tab? Vertical tab? Non-breaking space? The answer isn't always the same, either.

I'm fine collecting recipes for common cases like PEM and having them in the readme or something like that, but I don't think they're a good fit for inclusion in the library proper. I want to focus on making more use cases efficient and possible than on making a few use cases "easy", and a lot of these "filtering" type things are arguably better done in the i/o layer anyway. 

On top of all that, a `Read` impl that removes the exact bytes you want to ignore is a re-usable concept that also prevents you from having to allocate for the original string and then again for the filtered string, and despite being probably the implementation you actually want, is not something this library can do for you. So, let's move towards _that_ goal instead towards a layering violation that also constrains our implementation optimizations...

**Comment by timbru** [comment]
Ok. I see your point about the number of special cases and efficiency. Like I said, I can work around this with relative ease.
