### ISSUE TITLE
Should `decode_*` methods support decoding from a `&[u8]?`

### ISSUE THREAD

**Issue by marshallpierce** [alicemaz/rust-base64#16]
See https://github.com/alicemaz/rust-base64/pull/14/files#diff-b4aea3e418ccdb71239b96952d9cddb6R130

It seems unfortunate to force a user who has some (ascii) bytes that they wish to decode to `String`-ify them first (at the cost of verifying that the bytes are UTF8, or unsafely creating the string). In the decode logic we simply access the bytes of the string anyway, so it would be little work to expose decoding from bytes.

We already check for every possible invalid byte because the decode tables have 256 entries (with suitable invalid markers), so it wouldn't incur any additional checking beyond what we already have. Thoughts?

**Comment by nox** [comment]
This would be highly useful in Servo.
