### ISSUE TITLE
Display wrapper for base64 encoded value

### ISSUE THREAD

**Issue by tailhook** [alicemaz/rust-base64#17]
Basically, I want `Base64(&[u8])` that implements `std::fmt::Display` that formats into destination buffer without intermediate memory allocations:
```
write!(file, "Sec-WebSocket-Accept: {}", Base64(value))
```

What what do you think about this?

**Comment by marshallpierce** [comment]
I can definitely see the appeal. I assume heap allocation is what you want to avoid, not stack allocation?

In the current implementation, we get tremendous speed gains by writing into a buffer we control, but perhaps we can preserve the speed and do some of the buffer management for you. Perhaps if the wrapper Display struct had an array (say, 1K) and encoded its input in chunks into the array that were then emitted to the formatter, that would do the job. We would need to rework encoding a little bit to be able to output to a slice, and then converting an array full of utf-8 bytes into a Formatter, but I think it can be done.

**Comment by tailhook** [comment]
Yes. Sorry that I've missed comment. I understand your point about benchmarks. I've done similar to what you desribe [here](https://github.com/fizyk20/generic-array/pull/27/files). It works.

So should I make a pull request?

**Comment by marshallpierce** [comment]
Sorry for the delay; I'll take a look shortly

**Comment by marshallpierce** [comment]
Do you need to support line wrapping as part of this? Supporting line wrapping when encoding in chunks that don't necessarily line up well with line length is pretty complex, so if you don't need it, I'd just as soon not bother. Labor of love only goes so far... ;)

**Comment by tailhook** [comment]
No, I don't need line wrapping. Thanks for the hard work!

**Comment by dtolnay** [comment]
I would have wanted to use this to serialize base64 data with Serde in https://github.com/serde-rs/json/issues/360.

**Comment by marshallpierce** [comment]
#33 is merged. I'll release a new version with this and the other recently merged features once #48 gets merged or people convince me it's a bad idea.
