### ISSUE TITLE
Support for URL-safe decoding

### ISSUE THREAD

**Issue by djc** [alicemaz/rust-base64#2]
rustc-serialize supports three types of encoding:

MIME: Configuration for RFC 2045 MIME base64 encoding
STANDARD: Configuration for RFC 4648 standard base64 encoding
URL_SAFE: Configuration for RFC 4648 base64url encoding

In particular, I have a use case for URL-safe encoding/decoding.

**Comment by alicemaz** [comment]
Adding a mode for url-safe now, will likely get to MIME later this week and will close when that's complete. Thank you!

**Comment by alicemaz** [comment]
>later this week
:open_mouth: 

mime added with #19
