### ISSUE TITLE
Adding Apache2 license

### ISSUE THREAD

**Issue by pmarcelll** [alicemaz/rust-base64#24]
In [this thread](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485/20) about depecating `rustc-serialize` it was mentioned that this crate would be a good candidate for base64 encoding/decoding, but its license is not entirely compatible with the license of `rustc-serialize`.

Is it possible to add the Apache2 license as well?
Thanks

**Comment by marshallpierce** [comment]
FWIW Apache 2 is fine with me (as a contributor).

**Comment by alicemaz** [comment]
I don't see any reason why not. five minutes of googling seems to indicate I can just do this unilaterally, but I'll hold off a few days in case anyone who has contributed in the past (cc: @Stebalien @nox @tredoe @pmarcelll) has any objections

**Comment by Stebalien** [comment]
I consent.

**Comment by Keats** [comment]
Fine with me as well

**Comment by nox** [comment]
I consent, too.

**Comment by tredoe** [comment]
I consent, too.

**Comment by alicemaz** [comment]
that's consensus :+1:
