### ISSUE TITLE
line seperation behaves badly for non-empty buffers

### ISSUE THREAD

**Issue by alicemaz** [alicemaz/rust-base64#25]
(for now I wrapped it in `if orig_buf_len == 0` and published it as a patch so it doesn't mess up anyone's day)

so this is a thing that hadn't occurred to me at the time. since it just runs through the whole buffer adding line endings every n chars, data that's already there gets mutated, most often in an extremely undesirable manner. for instance mime-encoding a string that produces an output > 76, then encoding emptystring into the same buffer adds extra line seps

not sure the best way to handle this. the naive solution is to start counting from the starting point of the input, which _could_ make sense if the user were using a large string for assorted data (though the fact that we unconditionally write to the end would make this cumbersome, and anyway there are so much more barriers in the way of this compared to buffer sharing to dodge mallocs in C I don't see why one would do it in rust)

more likely I assume the user would be incrementally building a single item, in which case we would want to count from the _previous_ line sep, so as to always produce n-character lines with the final line unterminated (eg user produces 80 chars, we break after 76 for a length of 82, they add 80 more and we break again at 76*2+2 for 164). but making these kinds of assumptions about what already is in the buffer rather than encoding them into types makes the haskeller in me queasy and start wanting to implement yet another wrapper over strings

(incidental to this, the reserve calculation is wrong in the case where a non-empty buffer would be large enough to add even more line-endings, though only wrong in a "oops it doubles in capacity" and doesn't affect the fast loop)

**Comment by marshallpierce** [comment]
fyi I have completely reworked line wrapping in https://github.com/marshallpierce/rust-base64/tree/display-wrapper and it is now about 20x faster. PR coming soon! I'm pretty sure that branch does the right thing now for pre-existing input but I'm happy to add more test cases if you want to sketch some pseudo code of what you're specifically thinking of here.

**Comment by alicemaz** [comment]
I will try to find time to verify the cases I had in mind are valid here before leaving tmrw

**Comment by alicemaz** [comment]
I thought about this some and actually there isn't really a nontrivial way to get the "incrementally build encoded output" since aside from the line sep thing you'd in most cases need to merge the last few characters (eg taking `YXNkZg==` to `YXNkZmc=` to add a character). probably sensible to leave it alone absent a real usecase
