### ISSUE TITLE
encoded_size fixes

### ISSUE THREAD

**Issue by alicemaz** [alicemaz/rust-base64#28]
@marshallpierce I changed encoded_size to use checked arithmetic and return an Option with 24ead98. (there are a couple ways an attack using this could have been feasible, thank you to Andrew Ayer for reporting). presently its two callers will just panic on `None`. I'm inclined to think this is better than adding `Result` to encode returns since no non-malicious case of hitting usize max seems likely

also some of the linesize calculations involving are off slightly in non-dangerous ways, I'm gonna fix that and add more test cases after I can merge in your present PRs

**Comment by alicemaz** [comment]
oh and to be clear I already published this as a patch to 0.3-0.5

**Comment by marshallpierce** [comment]
OK. Note that I re-did the line wrapping calculations to be precise in all cases AFAIK instead of sometimes a little too conservative in their space requirements.

**Comment by alicemaz** [comment]
I will try to find time to verify the cases I had in mind are valid here before leaving tmrw
