### ISSUE TITLE
Only supports strings of length equal to or less than 32?

### ISSUE THREAD

**Issue by polarathene** [alicemaz/rust-base64#35]
A string greater than 32 characters/length seems to be unsupported?
```
let a = b"abcdefghijklmnopqrstuvwxyzABCDEFG";
let b = encode(a);
```

When compiling I get the error:
```
error[E0277]: the trait bound `[u8; 33]: std::convert::AsRef<[u8]>` is not satisfied

the trait `std::convert::AsRef<[u8]>` is not implemented for `[u8; 33]`

help: the following implementations were found:
             <[T] as std::convert::AsRef<[T]>>
             <[T; 0] as std::convert::AsRef<[T]>>
             <[T; 1] as std::convert::AsRef<[T]>>
             <[T; 2] as std::convert::AsRef<[T]>>
           and 30 others
   = note: required by `base64::encode`
```
The implementations would suggest that I guess. I'm new to Rust but I'd assume there would be a way to not have to continue new implementations for each additional length of the string to be supported?

**Comment by marshallpierce** [comment]
Just a quick note in passing; don't have time today to look into it -- since each array length is its own type, Rust only auto-implements the auto conversion to a slice for the first 32. There should be a method you can call to get a slice from it manually. Try the #rust-beginners IRC channel.

**Comment by polarathene** [comment]
Thanks the response was to provide a type eg:

```
let a: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFG";
```
