### ISSUE TITLE
Please add a ChangeLog file

### ISSUE THREAD

**Issue by linkmauve** [alicemaz/rust-base64#37]
This should be a short overview of per-release breaking changes and improvements, so that users know what to do when updating, and why.

**Comment by seanmonstar** [comment]
Alternatively, tag releases here: https://github.com/alicemaz/rust-base64/releases

**Comment by marshallpierce** [comment]
This is one of my least favorite aspects of Cargo -- it doesn't leave a VCS trail of when a release was actually performed to crates.io. I think a human-oriented changelog file would be nice, though.

**Comment by alicemaz** [comment]
I've been meaning to do this for awhile, can probably reconstruct one retroactive from the start. tagging releases would also be nice for if/when fixes have to backported, recently had to do this relying on Cargo.toml rev history. I'm in the middle of a cross-country move presently, will probably have time next week

**Comment by marshallpierce** [comment]
I pushed version tags.

**Comment by marshallpierce** [comment]
I think this is good now; re-open if the recently merged release notes aren't satisfactory.

**Comment by Emerentius** [comment]
Tags are not a solution to this at all. There is no info on what the changes are between versions. Presumably there were breaking changes between 0.12 and 0.13, how could a dependant of this library possibly find out without sifting through the commit log?

**Comment by marshallpierce** [comment]
If https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md isn't satisfactory you're entitled to a full refund.

**Comment by Emerentius** [comment]
Ah, sorry, I missed that.
