### ISSUE TITLE
In-place encoding/decoding.

### ISSUE THREAD

**Issue by quadrupleslap** [alicemaz/rust-base64#39]
This might sound really silly but I wish there were a way to encode/decode buffers in-place.

**Comment by marshallpierce** [comment]
It's reasonable enough. Can you provide more details on your use case? It's not out of the question to implement it (wouldn't be too hard) but I don't want to risk making the API confusing by offering every flavor of encoding/decoding under the sun if it's not really necessary.

**Comment by marshallpierce** [comment]
Idle; closing.
