### ISSUE TITLE
Add PartialEq to Error

### ISSUE THREAD

**Issue by tredoe** [alicemaz/rust-base64#7]
Add `#[derive(Debug, PartialEq)]` to the error so it could be compared in tests of other libraries/apps that use your library.

https://github.com/alicemaz/rust-base64/blob/master/src/lib.rs#L31

Thanks in advance!

**Comment by kless** [comment]
Some libraries add one more full:

`#[derive(PartialEq, Eq, Copy, Clone, Debug)]`

https://github.com/rust-lang-nursery/uuid/blob/master/src/lib.rs#L210

**Comment by kless** [comment]
https://www.reddit.com/r/rust/comments/5d8frm/traits_derived_in_errors/
