### ISSUE TITLE
Release update with recent safemem

### ISSUE THREAD

**Issue by kpcyrd** [alicemaz/rust-base64#71]
Hey!

we're currently looking into packaging base64 for debian and noticed the most recently release version of safemem is using an outdated dependency. While we can technically work around this by uploading an outdated version of safemem we would rather just use the most recent version instead. The current master is using the most recent version of safemem already, could you please consider looking into releasing an update?

Thanks a lot!

**Comment by marshallpierce** [comment]
Certainly; I’m traveling at the moment but in a week I can get to it.

**Comment by marshallpierce** [comment]
Done.
