### ISSUE TITLE
Standard Decoding with OpenSSL

### ISSUE THREAD

**Issue by drakeley** [alicemaz/rust-base64#73]
Hello!

I am currently experimenting with the different config options, and I am running into an issue where only the MIME type seems to be decodable with openssl.

For example, I am writing out the base64-encoded bytes with:
```rust
let mut buf = String::new();
base64::encode_config_buf(&bytes_to_encode, base64::MIME, &mut buf);
fs::write("/tmp/base64_mime.test", buf.clone()).unwrap();
```

And then I am trying to decode them with:
`openssl base64 -d -in /tmp/base64_mime.txt -out /tmp/out.test`

However, if I use any other Config enum, the size of the resulting out.test file is 0. 

The issue may not be with base64, but I'm wondering whether this should be expected, or if I am missing a step. The other candidate for causing this issue is in the way I am extracting the `bytes_to_encode`, which is below:

```rust
unsafe fn struct_as_u8(p: &MyStruct, size_of_struct: usize) -> &[u8] {
    ::std::slice::from_raw_parts(
        (p as *const MyStruct) as *const u8,
        size_of_struct
}
```
 
Note: `MyStruct` is a struct that contains other structs as well as byte arrays and primitive types.

Any help or intuition you could offer would be greatly appreciated!
Thanks!

**Comment by marshallpierce** [comment]
That certainly is pretty `unsafe`! :) Perhaps your unsafe code fails some of the time -- try writing the same bytes out to different files with different configs (i.e. in the same process -- not by editing the source and re-running).

**Comment by drakeley** [comment]
Hehe yes! Thank you for the quick reply. Regarding writing out a file for each base64 config type, that was how I was conducting the test. I also tried using bincode to write the raw bytes to a file, and the result of that matched byte-for-byte with the MIME encoding.

**Comment by marshallpierce** [comment]
Hm, interesting. Can you reduce it to a test case? There are a lot of tests for this library, including a good number of randomized ones, but maybe you've stumbled across some subtle bug?

**Comment by drakeley** [comment]
I will work on getting a test case together! Thanks again!

**Comment by marshallpierce** [comment]
also, just in case, try using `base64 -d` instead of `openssl base64`

**Comment by marshallpierce** [comment]
`base64` only supports the standard alphabet, so that's expected
