### ISSUE TITLE
Make emitting an error on decoding nonzero trailing bits optional

### ISSUE THREAD

**Issue by marshallpierce** [alicemaz/rust-base64#95]
The web, of course, needs sloppy decoding. https://infra.spec.whatwg.org/#forgiving-base64-decode

**Comment by nox** [comment]
I'm not sure what you decided to do with regard to the `Config` data structure, but I would be happy to help you make that change if you describe what you want the API to look like around that type.

**Comment by marshallpierce** [comment]
Thanks; I like your builder approach.

**Comment by nox** [comment]
For the entry point without `pad`, what do you think of an impl of `From<CharacterSet>` for `Config`?

```rust
Config::from(CharacterSet::Standard).forgiving(true)
```

**Comment by marshallpierce** [comment]
I think picking defaults like that opens up the possibility for regrettable confusion as future config changes come down the line. I'd rather have users be aware of what choices they're making explicitly. An extra line is a small price to pay for clarity IMO.

**Comment by nox** [comment]
@marshallpierce Ok, I'll leave `Config::new` alone then.

**Comment by marshallpierce** [comment]
Just to make sure I'm following you, where were you picturing the `From` impl being used?

**Comment by nox** [comment]
@marshallpierce Literally nowhere except where you make your own `CharacterSet`, which is not currently doable. :) It just seems weird to me to have a `new` method which has a parameter for one of the settings but not the others, but that's not very important anywy.

**Comment by nox** [comment]
What I also don't understand is that the spec for the forgiving algo mentions 12 or 18 trailing bits, while the code in `base64` seems to only talk about 6 bits, am I missing something?

**Comment by marshallpierce** [comment]
We could just ditch `new` entirely and make everyone use the builder, I suppose, and then it's at least very clear that you're accepting defaults for the stuff you don't specify.

I don't understand how it's possible to have 12 or 18 trailing bits, unless they're talking about padding?

**Comment by nox** [comment]
> I don't understand how it's possible to have 12 or 18 trailing bits, unless they're talking about padding?

No clue, I checked that my PR (#96) makes the tests pass again, didn't investigate further. :D
